### ISSUE TITLE
画面にコメントが流れてこない

### ISSUE THREAD

**Issue by shumon84** [Yukiho-YOSHIEDA/nico-test#1]
READMEにしたがって、
```
$ npm run install
$ npm run serve
```
を実行したあとに localhost:1234 にアクセスしましたが、画面にコメントが流れてきませんでした
consoleを確認したところ、以下のエラーが出力されていました
<img width="601" alt="screen_shot 2020-04-08 10 30 00" src="https://user-images.githubusercontent.com/21356918/78734905-70015180-7984-11ea-9b19-c4f931a4d1b3.png">
原因分かりますか

**Comment by Yukiho-YOSHIEDA** [comment]
まず、`$ npm run serve` はホットリロードなのでプログラムを終えるまで終えないでください。
正常起動中は以下のような画像になります。
![image](https://user-images.githubusercontent.com/38527548/78740918-f9b81b80-7992-11ea-9b83-c41e70cebf42.png)

動作確認環境は
* node.js v12.16.1
* Chrome
* FireFox

です。

蛇足だと思いますが、issueの教えていただいたコマンドがREADMEと異なるのでもう一度確認してみてください。

**Comment by shumon84** [comment]
あれ、なんか昨日と同じ手順でやったらコメント表示できてしまった
キャッシュかなんかが残ってたのかな

**Comment by Yukiho-YOSHIEDA** [comment]
解決したのでクローズします！

**Comment by shumon84** [comment]
あざす
